CREATE TABLE "email_templates" (
    "id" SERIAL NOT NULL,
    "eventType" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "subject" TEXT NOT NULL,
    "bodyHtml" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "email_templates_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "email_templates_eventType_key" ON "email_templates"("eventType");

-- Стартовые шаблоны (точно соответствуют тому, что было захардкожено).
INSERT INTO "email_templates" ("eventType", "label", "subject", "bodyHtml", "updatedAt") VALUES
('INQUIRY_RECEIVED',
 'Новая заявка с витрины (менеджеру)',
 'Новая заявка {{orderNumber}} с витрины',
 '<h2>Новая заявка {{orderNumber}}</h2><p><b>Клиент:</b> {{contactName}} ({{contactPhone}})</p><p><b>Email:</b> {{contactEmail}}</p><p><b>Оборудование:</b> {{equipmentName}}</p><p><b>Сообщение:</b><br>{{inquiryNote}}</p>',
 CURRENT_TIMESTAMP),
('ORDER_CREATED',
 'Новый заказ (менеджеру)',
 'Заказ {{orderNumber}} оформлен ({{source}})',
 '<h2>Заказ {{orderNumber}}</h2><p>Клиент: <b>{{clientName}}</b></p><p>Сумма: <b>{{totalAmount}}₽</b></p><p>Период: {{fromDate}} — {{toDate}}</p>',
 CURRENT_TIMESTAMP),
('ORDER_STATUS_CHANGED',
 'Изменение статуса заказа (клиенту)',
 'Статус заказа {{orderNumber}} изменён',
 '<p>Здравствуйте, {{clientName}}!</p><p>Статус заказа <b>{{orderNumber}}</b> изменён:<br><code>{{fromStatus}}</code> → <code>{{toStatus}}</code></p>',
 CURRENT_TIMESTAMP),
('ORDER_OVERDUE',
 'Просрочка возврата (клиенту и менеджеру)',
 'Просрочен возврат по заказу {{orderNumber}}',
 '<p>Здравствуйте, {{clientName}}!</p><p>Срок возврата по заказу <b>{{orderNumber}}</b> был <b>{{toDate}}</b>. Свяжитесь с нами для согласования возврата или продления.</p>',
 CURRENT_TIMESTAMP),
('ORDER_RETURN_REMINDER',
 'Напоминание о возврате (клиенту)',
 'Скоро возврат по заказу {{orderNumber}}',
 '<p>Здравствуйте, {{clientName}}!</p><p>Напоминаем: <b>{{toDate}}</b> — день возврата оборудования по заказу <b>{{orderNumber}}</b> (через {{daysLeft}} дн.).</p><p>Если планы изменились и нужно продлить аренду — свяжитесь с менеджером заранее.</p>',
 CURRENT_TIMESTAMP),
('ORDER_EXTENDED',
 'Продление аренды (клиенту)',
 'Заказ {{orderNumber}} продлён',
 '<p>Здравствуйте, {{clientName}}!</p><p>Заказ <b>{{orderNumber}}</b> продлён на <b>+{{addedDays}} дн.</b> до <b>{{newToDate}}</b>.<br>Доплата: <b>{{addedAmount}}₽</b>.</p>',
 CURRENT_TIMESTAMP),
('PASSWORD_RESET_CODE',
 'Код восстановления пароля (клиенту)',
 'Код для восстановления пароля',
 '<p>Здравствуйте, {{clientName}}!</p><p>Ваш одноразовый код для восстановления пароля:</p><p style="font-size:32px;letter-spacing:8px;font-weight:bold;font-family:monospace">{{code}}</p><p>Код действителен <b>{{ttlMinutes}} минут</b>. Если вы не запрашивали восстановление, проигнорируйте это письмо.</p>',
 CURRENT_TIMESTAMP),
('DAILY_OPS_BRIEF',
 'Утренняя сводка (менеджеру)',
 'Сводка на {{date}}: выдач {{pickupsCount}}, возвратов {{returnsCount}}',
 '<h2>Сводка на {{date}}</h2><ul><li>Сегодня выдач: <b>{{pickupsCount}}</b></li><li>Сегодня возвратов: <b>{{returnsCount}}</b></li><li>На руках просрочек: <b>{{overdueCount}}</b></li></ul>',
 CURRENT_TIMESTAMP);
